let data = {
    dataResep: require('./controller/dataResep'),
    getdataResep: require('./controller/getAllDataResep'),
    search: require('./controller/search'),
    detailResep: require('./controller/postDetailResep'),
    getdetailResep: require('./controller/getDetailRecep'),
    deleteAllDataResep: require('./controller/deleteAllDataResep'),
    deleteAllDataResepById: require('./controller/deleteDataResepById'),
    deleteAllDetailResep: require('./controller/deleteAllDetailResep'),
    regis: require('./controller/userRegister'),
    getDataUser: require('./controller/getUser'),
    login: require('./controller/login'),
    updateFavoritUser: require('./controller/userFavorit'),
    deleteFavoritUser: require('./controller/userFavoriteDelete'),
    artikelPost : require('./controller/aetikelPost'),
    getArtikel : require('./controller/getArtikelPost'),
    artikelDetailPost : require('./controller/postDetailArtikel'),
    searchDetailArtikel : require('./controller/searchDetailArtikel'),
    getAllDetailArtikel : require('./controller/getAllDetailArtikel'),
    postFoodInformation : require('./controller/postFoodInformation'),
    getAllFoodInformation : require('./controller/getAllFoodInformation'),
    postDetailFoodInformation : require('./controller/postDetailFoodInformation'),
    searchDetailFoodInformation : require('./controller/searchDetailFoodInformation'),
    postTrendFood : require('./controller/postTrendFood'),
    getTrendFood : require('./controller/getFoodTrend'),
    // hah: require('./view/hah'),
};

module.exports = data;